[mgr]
ratio = [1, 3, 4]
sort_by = "natural"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
linemode = "size"
show_hidden = true
show_symlink = true

[preview]
tab_size = 2
max_width = 2000
max_height = 2000
cache_dir = ""
image_filter = "nearest"
image_delay = 50
image_quality = 50
sixel_fraction = 15
ueberzug_scale = 1
ueberzug_offset = [0, 0, 0, 0]

[opener]
helix = [{ run = "hx %s", block = true, desc = "Open in Helix" }]

[open]
prepend_rules = [
  { mime = "inode/directory", use = "helix" },

  # Open all text files in Helix
  { mime = "text/*", use = "helix" },

  # Open empty files in Helix
  { mime = "inode/x-empty", use = "helix" }
]
