
theme = "catppuccin_mocha"
# theme = "catppuccin_transparent"
# theme = "onedark_transparent"

[editor]
line-number = "relative"
bufferline = "multiple"
default-yank-register = "+"
auto-pairs = false
text-width = 80
mouse = false
cursorline = false
color-modes = true
true-color = true
scrolloff = 10
end-of-line-diagnostics = "hint"
idle-timeout = 50
completion-timeout = 50

[editor.inline-diagnostics]
cursor-line = "hint"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.soft-wrap]
enable = true
max-wrap = 25 # increase value to reduce forced mid-word wrapping
max-indent-retain = 0
# wrap-indicator = ""  # set wrap-indicator to "" to hide it


[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
C-c = ["collapse_selection", "keep_primary_selection"]
C-h = "jump_view_left"
C-j = "jump_view_down"
C-k = "jump_view_up"
C-l = "jump_view_right"
S-l = "goto_next_buffer"
S-h = "goto_previous_buffer"
"{" = ["goto_prev_paragraph"]
"}" = ["goto_next_paragraph"]
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
C-e = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]
"C-/" = "toggle_comments"

[keys.insert]
C-c = "normal_mode"

[keys.normal.g]
# a = "code_action"


[keys.select]
"{" = ["goto_prev_paragraph"]
"}" = ["goto_next_paragraph"]
