[[language]]
name = "go"
auto-format = true
language-servers = ["gopls"]

[[language]]
name = "templ"
scope = "source.templ"
injection-regex = "templ"
file-types = ["templ"]
roots = ["go.mod"]
language-servers = ["templ", "gopls"]

[[language]]
name = "typescript"
auto-format = true
language-servers = ["typescript-language-server"]

[[language]]
name = "javascript"
indent = { tab-width = 4, unit = " " }
auto-format = true
language-servers = ["typescript-language-server"]

[[language]]
name = "json"
auto-format = true
language-servers = ["vscode-json-language-server"]

[[language]]
name = "c-sharp"
scope = "source.cs"
roots = ["*.sln", "*.csproj"]
language-servers = ["omnisharp"]

[[language]]
name = "python"
language-servers = ["ruff", "pyright"]
formatter = { command = "ruff", args = ["format", "-"] }
auto-format = true

[language-server.templ]
command = "templ"
args = ["lsp"]

[language-server.gopls]
command = "gopls"

[language-server.vscode-json-language-server]
command = "vscode-json-language-server"
args = ["--stdio"]

[language-server.omnisharp]
command = "OmniSharp"
args = ["--languageserver", "--hostPID", "0"]

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.ruff]
command = "ruff"
args = ["server"]
