Section "InputClass"
    Identifier "Mouse and Touchpad"
    MatchIsPointer "yes"
    Option "libinput Accel Speed" "1.0"
EndSection

Section "InputClass"
    Identifier "Touchpad"
    MatchIsTouchpad "yes"
    Option "libinput Accel Speed" "1.0"
EndSection
