
general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances
    before_sleep_cmd = loginctl lock-session    # lock before suspending
    after_sleep_cmd = hyprctl dispatch dpms on  # turn screen on after waking up
}

# 1. Dim the screen after 2.5 minutes of inactivity
listener {
    timeout = 150                                
    on-timeout = brightnessctl -s set 10         # set monitor backlight to 10%
    on-resume = brightnessctl -r                 # restore monitor backlight
}

# 2. Lock the screen after 5 minutes
listener {
    timeout = 300                                 
    on-timeout = loginctl lock-session            
}

# 3. Turn off the screen after 5.5 minutes
listener {
    timeout = 330                                 
    on-timeout = hyprctl dispatch dpms off        
    on-resume = hyprctl dispatch dpms on          
}

# 4. Suspend the laptop after 15 minutes
listener {
    timeout = 900                                 
    on-timeout = systemctl suspend                
}
