
#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

exec-once = $terminal
exec-once = hyprpaper
exec-once = hypridle
exec-once = waybar
exec-once = swaync

exec-once = kmonad ~/.config/kmonad/config.kbd
exec-once = systemctl --user start hyprpolkitagent
exec-once = nm-applet
exec-once = blueman-applet

# Clipboard Manager Listeners
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

exec-once = hyprctl setcursor catppuccin-mocha-rosewater-cursors 24
