##############################
########## WINDOWS ###########
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrules that are useful


windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

# Force opacity for Ghostty
# windowrule {
#     name = force-ghostty-opacity
#     match:class = com.mitchellh.ghostty

#     # Active window 80% opaque, inactive window 70% opaque
#     opacity = 0.9 0.7
# }

# # Force opacity for Kitty
# windowrule {
#     name = force-kitty-opacity
#     match:class = kitty

#     # Active window 80% opaque, inactive window 70% opaque
#     opacity = 0.8 0.7
# }
