# More option see https://github.com/DreamMaoMao/mango/wiki/

source=./modules/environment.conf
source=./modules/autostart.conf
source=./modules/monitor.conf
source=./modules/input.conf
source=./modules/binds.conf
source=./modules/animation.conf
source=./modules/decoration.conf
source=./modules/layout.conf
source=./modules/overview.conf
source=./modules/miscellaneous.conf
source=./modules/windowrule.conf
