# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0x000000ff
rootcolor = 0x131313ff
bordercolor = 0x919191ff
focuscolor = 0xffb5a0ff
maximizescreencolor = 0xe7bdb2ff
urgentcolor = 0xffb4abff
scratchpadcolor = 0xd9c58dff
globalcolor = 0x7c2d16ff
overlaycolor = 0x5d4038ff
