
exec-once=qs -c noctalia-shell
exec-once=kmonad ~/.config/kmonad/config.kbd
exec-once=wlr-randr --output eDP-1 --custom-mode 2560x1600@60
exec-once=~/.config/mango/scripts/idle.sh
exec-once=dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
