#monitorrule=name:eDP-1,width:2880,height:1800,refresh:120,scale:1.5
monitorrule=name:eDP-1,width:2560,height:1600,refresh:60,scale:1.25
#monitorrule=name:eDP-1,width:2560,height:1600,refresh:120,scale:1.25
#monitorrule=name:eDP-1,width:1920,height:1200,refresh:60,scale:1
#monitorrule=name:eDP-1,width:1920,height:1200,refresh:120,scale:1
