# To find appid use the command below
# mmsg -w -c


windowrule=appid:satty,isfloating:1

windowrule=appid:^(PacketTracer)$,isfloating:1,width:500
windowrule=appid:Pinentry-gtk,isfloating:1


# AutoStart on Boot
windowrule=appid:discord,tags:8
windowrule=appid:zen,tags:1
windowrule=appid:foot-boot,tags:3
